USE [Test_DB]
GO



CREATE TABLE [dbo].[STG_SUNAT_TC](
	[Fecha] [date] NOT NULL,
	[Compra] [money] NOT NULL,
	[Venta] [money] NOT NULL,
 CONSTRAINT [PK_STG_SUNAT_TC] PRIMARY KEY CLUSTERED 
(
	[Fecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[M_SUNAT_TC](
	[Fecha] [date] NOT NULL,
	[Compra] [money] NOT NULL,
	[Venta] [money] NOT NULL,
	[Estimado] [bit] NOT NULL,
 CONSTRAINT [PK_M_SUNAT_TC] PRIMARY KEY CLUSTERED 
(
	[Fecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

